name: pywwc
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - netcdf4
  - zarr
  - numpy
  - dask
  - matplotlib
  - fsspec
  - aiohttp
  - pooch
  - fiona
  - pyogrio
  - geopandas
  - rioxarray
  - cartopy
  - holoviews
  - geoviews
  - jupyter
  - jupyterlab
  - jupyter-book
  - pip
  - pip:
    - jupyterlab-myst
